repocache: implement refs hack for fetching
Allows fetching/cloning remote repositories that have refs/heads/*
pointing to tag. The hack is disabled, by default.

Gerrit allows setting refs/heads/* pointing to tag objects. However, git
prevents this causing problems for repocache. Fetch will fail with
something like:
  error: Trying to write non-commit object x to branch refs/heads/y

A hackish workaround for this is to make GIT_DIR/refs a symlink. Then,
first fetch to GIT_DIR/refs.alt/fetch/* and then symlink GIT_DIR/refs to
point to GIT_DIR/refs.alt/fetch/.

The symlink hack in filesystem is automatically removed from the cached
repository if a CachedRepository instance (using the same cached repo)
is created with the hack disabled.

Change-Id: I1addf10fa5f805ab8f2b696e8ccaad9e56967bd0
Signed-off-by: Markus Lehtonen <markus.lehtonen@linux.intel.com>